FROM zhangsiy/win-core-dev:0.1.0
# add package folder to container
ADD . ./app
# set up working directory
WORKDIR /app
# Reinstall all npm modules including local gulp
RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "Remove-Item -Recurse -Force ./node_modules"
RUN npm install
# Remove src folder to allow mounting. See https://github.com/Microsoft/Virtualization-Documentation/issues/497#issuecomment-262636687
RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "Remove-Item -Recurse -Force ./src"
# Do the build
CMD gulp publish